name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-for-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build
      run: cd src && ./build.sh
      
    - name: Archive built app
      uses: actions/upload-artifact@v2
      with:
        name: net-file-share
        path: src/build/src
